name: 'styleguide'
description: 'Runs styleguide as a Github Action'
branding:
  icon: 'check'
  color: 'green'

inputs:
  path:
    description: 'Path or space-separated list of paths to lint'
    required: false
    default: '.'
  reporter:
    description: 'How would you like the results to be displayed?'
    required: false
    default: 'terminal'
  settings:
    description: 'Path to the settings file'
    required: true

outputs:
  output:
    description: 'The output of styleguide run'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.reporter }}
    - ${{ inputs.settings }}
